### ISSUE TITLE
Format static codebase using prettier

### ISSUE THREAD

**Issue by yankeexe** [GolangNepal/golangnepal.github.io#2]
Use prettier for formatting static HTML files on the codebase.

**Resources**: 
* [Prettier](https://prettier.io/)

**Comment by Aju100** [comment]
@yankeexe  assign me this. I will do it

**Comment by Aju100** [comment]
@yankeexe brother Here is the update https://github.com/GolangNepal/golangnepal.github.io/pull/4.
